channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python>=3.10.13
  - numpy==1.26.4
  - PyAutoGUI==0.9.54
  - pyperclip==1.8.2
  - pywinauto==0.6.8
  - PyYAML==6.0
  - pygame==2.5.2
  - flet==0.21.1
  - nodejs==20.9.0

  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - playwright==1.42.0
rccPostInstall:
  - playwright install chromium
