channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python
  - numpy==1.24.1
  - PyAutoGUI==0.9.53
  - pyperclip==1.8.2
  - pywinauto==0.6.8
  - PyYAML==6.0
  - pysimplegui==4.60.4 
  - pygame==2.5.0
  - pip

  - pip:

    # Define pip packages here. 
    # https://pypi.org/
    - flet==0.9.0
